#!/usr/bin/env python3
"""Standalone application for the "Default" project.

Auto-generated by Vision Studio. Reads config.json next to this file (or, once
frozen by Build Application, next to the executable) and nothing else - no
hardcoded thresholds/paths. This same script is both the dev-mode runtime
(`python runtime.py ...`) and the PyInstaller entry point used by Build
Application; app_dir() below makes both cases resolve paths identically.

Usage:
  runtime.py --video path/to/video.mp4
  runtime.py --image path/to/image.jpg
  runtime.py --camera 0
  runtime.py --rtsp rtsp://host/stream
  (no args: uses camera.* from config.json as-is)
"""
import argparse
import csv
import json
import logging
import os
import sys
import time
from datetime import datetime


def app_dir():
    """Directory to resolve config.json/labels.txt/output/logs against.
    Frozen (PyInstaller onefile): the exe's own directory, NOT sys._MEIPASS
    (which is a throwaway extraction temp dir) - config.json ships alongside
    the exe, not bundled inside it. Unfrozen: this script's directory."""
    if getattr(sys, "frozen", False):
        return os.path.dirname(sys.executable)
    return os.path.dirname(os.path.abspath(__file__))


_APP_DIR = app_dir()

if not getattr(sys, "frozen", False):
    _REPO_ROOT = os.path.abspath(os.path.join(_APP_DIR, "..", ".."))
    sys.path.insert(0, _REPO_ROOT)

import cv2

from camera.video_stream import VideoStream
from pipeline.vision_pipeline import VisionPipeline
from utils.event_logger import EventLogger
from utils.recorder import Recorder
from utils.snapshot import save_snapshot

CONFIG_PATH = os.path.join(_APP_DIR, "config.json")


def load_config():
    with open(CONFIG_PATH, encoding="utf-8") as f:
        return json.load(f)


def setup_logging(level_name, log_dir):
    os.makedirs(log_dir, exist_ok=True)
    level = getattr(logging, str(level_name).upper(), logging.INFO)
    logging.basicConfig(
        level=level,
        format="%(asctime)s [%(levelname)s] %(message)s",
        handlers=[
            logging.FileHandler(os.path.join(log_dir, "runtime.log")),
            logging.StreamHandler(sys.stdout),
        ],
    )
    return logging.getLogger("runtime")


def write_report(output_dir, project_name, source, duration_s, counts):
    report = {
        "project": project_name,
        "timestamp": datetime.now().isoformat(timespec="seconds"),
        "source": str(source),
        "duration_seconds": round(duration_s, 2),
        "total_in": counts["total_in"],
        "total_out": counts["total_out"],
        "total": counts["total"],
    }
    with open(os.path.join(output_dir, "report.json"), "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2)
    csv_path = os.path.join(output_dir, "report.csv")
    write_header = not os.path.exists(csv_path)
    with open(csv_path, "a", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(report.keys()))
        if write_header:
            writer.writeheader()
        writer.writerow(report)


def run_image_mode(image_path, cfg, pipeline, output_dir, logger):
    frame = cv2.imread(image_path)
    if frame is None:
        logger.error(f"could not read image: {image_path}")
        sys.exit(1)

    t0 = time.time()
    annotated, tracks, events, stats, debug = pipeline.process(frame, cfg)
    stem = os.path.splitext(os.path.basename(image_path))[0]
    out_path = os.path.join(output_dir, f"{stem}_annotated.jpg")
    cv2.imwrite(out_path, annotated)
    logger.info(f"processed image {image_path} -> {out_path}")

    counts = pipeline.line_counter.get_counts(cfg["counting"]["lines"])
    write_report(output_dir, cfg["project"]["name"], image_path, time.time() - t0, counts)
    logger.info(f"counts: IN={counts['total_in']} OUT={counts['total_out']} TOTAL={counts['total']}")


def run_stream_mode(cfg, pipeline, output_dir, logger, show_window, forced_single_pass, annotate_video_path):
    camera = VideoStream(cfg["camera"])
    camera.start()

    event_logger = EventLogger(_APP_DIR, cfg["output"])
    recorder = Recorder(base_dir=output_dir)

    video_writer_started = False
    if annotate_video_path or cfg["output"].get("save_videos"):
        recorder.start(cfg["camera"]["width"], cfg["camera"]["height"], cfg["camera"]["fps"])
        video_writer_started = True

    frame_skip = max(0, int(cfg.get("performance", {}).get("frame_skip", 0)))
    frame_counter = 0
    t0 = time.time()

    logger.info("runtime started" + (" (single pass)" if forced_single_pass else " - Ctrl-C to stop"))
    try:
        while True:
            if camera.ended:
                logger.info("source finished - stopping")
                break

            frame = camera.get_frame()
            if frame is None:
                time.sleep(0.02)
                continue

            frame_counter += 1
            if frame_skip > 0 and frame_counter % (frame_skip + 1) != 0:
                continue

            annotated, tracks, events, stats, debug = pipeline.process(frame, cfg)

            for event in events:
                event_logger.log(event)
                if cfg["output"].get("save_snapshots"):
                    save_snapshot(annotated, folder=os.path.join(output_dir, "snapshots"))

            if recorder.is_recording:
                recorder.write(annotated)

            if show_window:
                cv2.imshow(cfg["project"]["name"], annotated)
                if cv2.waitKey(1) & 0xFF == 27:
                    break
    except KeyboardInterrupt:
        logger.info("interrupted by user")
    finally:
        camera.stop()
        saved_name = recorder.stop() if video_writer_started else None
        if saved_name and annotate_video_path:
            produced = os.path.join(output_dir, saved_name)
            if os.path.exists(produced):
                os.replace(produced, annotate_video_path)
        if show_window:
            cv2.destroyAllWindows()

        counts = pipeline.line_counter.get_counts(cfg["counting"]["lines"])
        write_report(output_dir, cfg["project"]["name"], cfg["camera"]["source"], time.time() - t0, counts)
        logger.info(f"total counted: IN={counts['total_in']} OUT={counts['total_out']} TOTAL={counts['total']}")
        logger.info("runtime stopped")


def main():
    parser = argparse.ArgumentParser(description="Vision Studio standalone application")
    parser.add_argument("--image", help="process a single image and exit")
    parser.add_argument("--video", help="process a video file (single pass)")
    parser.add_argument("--camera", type=int, help="USB camera index")
    parser.add_argument("--rtsp", help="RTSP/IP camera URL")
    parser.add_argument("--output", help="override output directory")
    parser.add_argument("--display", action="store_true", help="show a debug window")
    args = parser.parse_args()

    cfg = load_config()

    output_dir = args.output or os.path.join(_APP_DIR, cfg["output"].get("output_folder", "output"))
    os.makedirs(output_dir, exist_ok=True)
    logger = setup_logging(cfg.get("logging", {}).get("level", "info"), os.path.join(_APP_DIR, "logs"))

    if args.image:
        pipeline = VisionPipeline()
        run_image_mode(os.path.abspath(args.image), cfg, pipeline, output_dir, logger)
        return

    forced_single_pass = False
    annotate_video_path = None

    if args.video:
        # Absolute path: CLI-supplied sources are relative to the caller's cwd,
        # never to this app's own directory - resolving otherwise breaks once
        # frozen (there is no meaningful "repo root" inside a PyInstaller bundle).
        cfg["camera"]["source_type"] = "file"
        cfg["camera"]["source"] = os.path.abspath(args.video)
        cfg["camera"]["loop"] = False
        forced_single_pass = True
        stem = os.path.splitext(os.path.basename(args.video))[0]
        annotate_video_path = os.path.join(output_dir, f"{stem}_annotated.mp4")
    elif args.camera is not None:
        cfg["camera"]["source_type"] = "usb"
        cfg["camera"]["source"] = str(args.camera)
    elif args.rtsp:
        cfg["camera"]["source_type"] = "rtsp"
        cfg["camera"]["source"] = args.rtsp

    show_window = args.display or cfg["output"].get("show_window", False)
    pipeline = VisionPipeline()
    run_stream_mode(cfg, pipeline, output_dir, logger, show_window, forced_single_pass, annotate_video_path)


if __name__ == "__main__":
    main()
