#!/usr/bin/env python3
"""Standalone production runtime for the "Default" project.

Auto-generated by Vision Studio — reads config.json next to this file and
nothing else. No hardcoded thresholds/paths: re-tune in the Studio and hit
Save Configuration to regenerate this file (or just edit config.json by hand
and re-run — this script re-reads it fresh on every launch).
"""
import argparse
import json
import os
import sys
import time

_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_REPO_ROOT = os.path.abspath(os.path.join(_THIS_DIR, "..", ".."))
sys.path.insert(0, _REPO_ROOT)

import cv2

from camera.video_stream import VideoStream
from pipeline.vision_pipeline import VisionPipeline
from utils.event_logger import EventLogger
from utils.recorder import Recorder
from utils.snapshot import save_snapshot

CONFIG_PATH = os.path.join(_THIS_DIR, "config.json")


def load_config():
    with open(CONFIG_PATH) as f:
        return json.load(f)


def main():
    parser = argparse.ArgumentParser(description="Vision Studio production runtime")
    parser.add_argument("--display", action="store_true", help="show a debug window")
    args = parser.parse_args()

    cfg = load_config()
    output_cfg = cfg["output"]
    output_dir = os.path.join(_THIS_DIR, output_cfg.get("output_folder", "output"))
    snapshot_dir = os.path.join(output_dir, "snapshots")
    os.makedirs(output_dir, exist_ok=True)

    camera = VideoStream(cfg["camera"])
    camera.start()

    pipeline = VisionPipeline()
    logger = EventLogger(_THIS_DIR, output_cfg)
    recorder = Recorder(base_dir=output_dir)

    show_window = args.display or output_cfg.get("show_window", False)
    if output_cfg.get("save_videos"):
        recorder.start(cfg["camera"]["width"], cfg["camera"]["height"], cfg["camera"]["fps"])

    frame_skip = max(0, int(cfg.get("performance", {}).get("frame_skip", 0)))
    frame_counter = 0

    print(f"[{cfg['project']['name']}] runtime started. Ctrl-C to stop.")
    try:
        while True:
            frame = camera.get_frame()
            if frame is None:
                time.sleep(0.02)
                continue

            frame_counter += 1
            if frame_skip > 0 and frame_counter % (frame_skip + 1) != 0:
                continue

            annotated, tracks, events, stats, debug = pipeline.process(frame, cfg)

            for event in events:
                logger.log(event)
                if output_cfg.get("save_snapshots"):
                    save_snapshot(annotated, folder=snapshot_dir)

            if recorder.is_recording:
                recorder.write(annotated)

            if show_window:
                cv2.imshow(cfg["project"]["name"], annotated)
                if cv2.waitKey(1) & 0xFF == 27:
                    break
    except KeyboardInterrupt:
        pass
    finally:
        camera.stop()
        recorder.stop()
        if show_window:
            cv2.destroyAllWindows()
        print(f"[{cfg['project']['name']}] runtime stopped.")


if __name__ == "__main__":
    main()
