#!/usr/bin/env python3
"""Standalone application for the "Bottle Counter" project.

Auto-generated by Vision Studio. Reads config.json next to this file (or, once
frozen by Build Application, next to the executable) and nothing else - no
hardcoded thresholds/paths. This same script is both the dev-mode runtime
(`python runtime.py ...`) and the PyInstaller entry point used by Build
Application; app_dir() below makes both cases resolve paths identically.

Usage:
  runtime.py --video path/to/video.mp4
  runtime.py --video path/to/video.mp4 --loop --display
  runtime.py --image path/to/image.jpg
  runtime.py --camera 0
  runtime.py --rtsp rtsp://host/stream
  (no args: uses camera.* from config.json as-is)

  --loop replays a --video source continuously (Ctrl-C to stop) instead of
  exiting after one pass - useful for watching counting behavior repeatedly
  while tuning. Add --display to see the annotated feed live.
  --stats-interval N logs session_total/in/out/objects_per_min/live_count/
  avg_confidence/fps/proc_ms/cpu/ram/pi_temp every N seconds (default 5).
"""
import argparse
import csv
import json
import logging
import os
import sys
import time
from collections import deque
from datetime import datetime


def app_dir():
    """Directory to resolve config.json/labels.txt/output/logs against.
    Frozen (PyInstaller onefile): the exe's own directory, NOT sys._MEIPASS
    (which is a throwaway extraction temp dir) - config.json ships alongside
    the exe, not bundled inside it. Unfrozen: this script's directory."""
    if getattr(sys, "frozen", False):
        return os.path.dirname(sys.executable)
    return os.path.dirname(os.path.abspath(__file__))


_APP_DIR = app_dir()

if not getattr(sys, "frozen", False):
    _REPO_ROOT = os.path.abspath(os.path.join(_APP_DIR, "..", ".."))
    sys.path.insert(0, _REPO_ROOT)

import cv2

from camera.video_stream import VideoStream
from pipeline.vision_pipeline import VisionPipeline
from utils.event_logger import EventLogger
from utils.recorder import Recorder
from utils.snapshot import save_snapshot
from utils.system_stats import get_system_stats

CONFIG_PATH = os.path.join(_APP_DIR, "config.json")


def load_config():
    with open(CONFIG_PATH, encoding="utf-8") as f:
        return json.load(f)


def setup_logging(level_name, log_dir):
    os.makedirs(log_dir, exist_ok=True)
    level = getattr(logging, str(level_name).upper(), logging.INFO)
    logging.basicConfig(
        level=level,
        format="%(asctime)s [%(levelname)s] %(message)s",
        handlers=[
            logging.FileHandler(os.path.join(log_dir, "runtime.log")),
            logging.StreamHandler(sys.stdout),
        ],
    )
    return logging.getLogger("runtime")


def write_report(output_dir, project_name, source, duration_s, counts):
    report = {
        "project": project_name,
        "timestamp": datetime.now().isoformat(timespec="seconds"),
        "source": str(source),
        "duration_seconds": round(duration_s, 2),
        "total_in": counts["total_in"],
        "total_out": counts["total_out"],
        "total": counts["total"],
    }
    with open(os.path.join(output_dir, "report.json"), "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2)
    csv_path = os.path.join(output_dir, "report.csv")
    write_header = not os.path.exists(csv_path)
    with open(csv_path, "a", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(report.keys()))
        if write_header:
            writer.writeheader()
        writer.writerow(report)


def run_image_mode(image_path, cfg, pipeline, output_dir, logger):
    frame = cv2.imread(image_path)
    if frame is None:
        logger.error(f"could not read image: {image_path}")
        sys.exit(1)

    t0 = time.time()
    annotated, tracks, events, stats, debug = pipeline.process(frame, cfg)
    stem = os.path.splitext(os.path.basename(image_path))[0]
    out_path = os.path.join(output_dir, f"{stem}_annotated.jpg")
    cv2.imwrite(out_path, annotated)
    logger.info(f"processed image {image_path} -> {out_path}")

    counts = pipeline.line_counter.get_counts(cfg["counting"]["lines"])
    write_report(output_dir, cfg["project"]["name"], image_path, time.time() - t0, counts)
    logger.info(f"counts: IN={counts['total_in']} OUT={counts['total_out']} TOTAL={counts['total']}")


def run_stream_mode(cfg, pipeline, output_dir, logger, show_window, forced_single_pass, annotate_video_path, stats_interval):
    camera = VideoStream(cfg["camera"])
    camera.start()

    event_logger = EventLogger(_APP_DIR, cfg["output"])
    recorder = Recorder(base_dir=output_dir)

    video_writer_started = False
    if annotate_video_path or cfg["output"].get("save_videos"):
        recorder.start(cfg["camera"]["width"], cfg["camera"]["height"], cfg["camera"]["fps"])
        video_writer_started = True

    frame_skip = max(0, int(cfg.get("performance", {}).get("frame_skip", 0)))
    frame_counter = 0
    t0 = time.time()

    fps_window = deque(maxlen=30)
    crossing_times = deque()
    last_loop_time = time.time()
    last_stats_log = time.time()

    looping_video = cfg["camera"]["source_type"] == "file" and cfg["camera"].get("loop")
    if forced_single_pass:
        mode_msg = " (single pass)"
    elif looping_video:
        mode_msg = " (looping video - Ctrl-C to stop)"
    else:
        mode_msg = " - Ctrl-C to stop"
    logger.info("runtime started" + mode_msg)
    try:
        while True:
            if camera.ended:
                logger.info("source finished - stopping")
                break

            frame = camera.get_frame()
            if frame is None:
                time.sleep(0.02)
                continue

            frame_counter += 1
            if frame_skip > 0 and frame_counter % (frame_skip + 1) != 0:
                continue

            t_proc0 = time.time()
            annotated, tracks, events, stats, debug = pipeline.process(frame, cfg)
            proc_ms = (time.time() - t_proc0) * 1000

            now = time.time()
            for _ in events:
                crossing_times.append(now)
            while crossing_times and now - crossing_times[0] > 60:
                crossing_times.popleft()

            loop_dt = now - last_loop_time
            last_loop_time = now
            fps_window.append(1.0 / loop_dt if loop_dt > 0 else 0.0)

            for event in events:
                event_logger.log(event)
                if cfg["output"].get("save_snapshots"):
                    save_snapshot(annotated, folder=os.path.join(output_dir, "snapshots"))

            if recorder.is_recording:
                recorder.write(annotated)

            if show_window:
                cv2.imshow(cfg["project"]["name"], annotated)
                if cv2.waitKey(1) & 0xFF == 27:
                    break

            if stats_interval > 0 and now - last_stats_log >= stats_interval:
                last_stats_log = now
                counts = stats.get("counts", {"total_in": 0, "total_out": 0, "total": 0})
                sys_stats = get_system_stats()
                fps = sum(fps_window) / len(fps_window) if fps_window else 0.0
                temp = sys_stats["temp_c"]
                logger.info(
                    "stats: session_total=%d in=%d out=%d objects_per_min=%d live_count=%d "
                    "avg_confidence=%.2f fps=%.1f proc_ms=%.1f cpu=%.0f%% ram=%.0f%% pi_temp=%s"
                    % (
                        counts.get("total", 0), counts.get("total_in", 0), counts.get("total_out", 0),
                        len(crossing_times), stats.get("object_count_current", len(tracks)),
                        stats.get("avg_confidence", 0.0), fps, proc_ms,
                        sys_stats["cpu_percent"], sys_stats["ram_percent"],
                        f"{temp}C" if temp is not None else "-",
                    )
                )
    except KeyboardInterrupt:
        logger.info("interrupted by user")
    finally:
        camera.stop()
        saved_name = recorder.stop() if video_writer_started else None
        if saved_name and annotate_video_path:
            produced = os.path.join(output_dir, saved_name)
            if os.path.exists(produced):
                os.replace(produced, annotate_video_path)
        if show_window:
            cv2.destroyAllWindows()

        counts = pipeline.line_counter.get_counts(cfg["counting"]["lines"])
        write_report(output_dir, cfg["project"]["name"], cfg["camera"]["source"], time.time() - t0, counts)
        logger.info(f"total counted: IN={counts['total_in']} OUT={counts['total_out']} TOTAL={counts['total']}")
        logger.info("runtime stopped")


def main():
    parser = argparse.ArgumentParser(description="Vision Studio standalone application")
    parser.add_argument("--image", help="process a single image and exit")
    parser.add_argument("--video", help="process a video file (single pass unless --loop)")
    parser.add_argument("--loop", action="store_true", help="replay --video continuously instead of stopping after one pass (Ctrl-C to stop)")
    parser.add_argument("--camera", type=int, help="USB camera index")
    parser.add_argument("--rtsp", help="RTSP/IP camera URL")
    parser.add_argument("--output", help="override output directory")
    parser.add_argument("--display", action="store_true", help="show a debug window")
    parser.add_argument("--stats-interval", type=float, default=None, help="seconds between periodic stats log lines (default: from config, else 5s; 0 disables)")
    args = parser.parse_args()

    cfg = load_config()

    output_dir = args.output or os.path.join(_APP_DIR, cfg["output"].get("output_folder", "output"))
    os.makedirs(output_dir, exist_ok=True)
    logger = setup_logging(cfg.get("logging", {}).get("level", "info"), os.path.join(_APP_DIR, "logs"))

    if args.image:
        pipeline = VisionPipeline()
        run_image_mode(os.path.abspath(args.image), cfg, pipeline, output_dir, logger)
        return

    forced_single_pass = False
    annotate_video_path = None

    if args.video:
        # Absolute path: CLI-supplied sources are relative to the caller's cwd,
        # never to this app's own directory - resolving otherwise breaks once
        # frozen (there is no meaningful "repo root" inside a PyInstaller bundle).
        cfg["camera"]["source_type"] = "file"
        cfg["camera"]["source"] = os.path.abspath(args.video)
        cfg["camera"]["loop"] = args.loop
        forced_single_pass = not args.loop
        if not args.loop:
            stem = os.path.splitext(os.path.basename(args.video))[0]
            annotate_video_path = os.path.join(output_dir, f"{stem}_annotated.mp4")
    elif args.camera is not None:
        cfg["camera"]["source_type"] = "usb"
        cfg["camera"]["source"] = str(args.camera)
    elif args.rtsp:
        cfg["camera"]["source_type"] = "rtsp"
        cfg["camera"]["source"] = args.rtsp

    show_window = args.display or cfg["output"].get("show_window", False)
    stats_interval = args.stats_interval
    if stats_interval is None:
        stats_interval = cfg.get("output", {}).get("stats_interval_s", 5.0)
    pipeline = VisionPipeline()
    run_stream_mode(cfg, pipeline, output_dir, logger, show_window, forced_single_pass, annotate_video_path, stats_interval)


if __name__ == "__main__":
    main()
